#!/usr/bin/with-contenv bash
cat <<"EOF"
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
         _               _
    __ _| |__   ___  ___| |_
   / _` | '_ \ / _ \/ __| __/
  | (_| | | | | (_) \__ \ |_
   \__, |_| |_|\___/|___/\__|
   |___/      /   _ \
          (¯\| o (@) |/¯)
           \_  .___.  _/
            /   !_!   \
           /_.--._.--._\

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
EOF

QBIT_WEBUI_USER=${QBIT_WEBUI_USER:-admin}
QBIT_WEBUI_PASS=${QBIT_WEBUI_PASS:-adminadmin}
QBIT_CONNECTION_PORT=${QBIT_CONNECTION_PORT:-6881}
QBIT_WEBUI_PASS_PBKDF2=$(echo -n ${QBIT_WEBUI_PASS} | base64 | xargs python3 /usr/local/bin/password-generator.py)
QBIT_MAX_RETENTION=${QBIT_MAX_RETENTION:-43200}
QBIT_MAX_RATIO=${QBIT_MAX_RATIO:-10}

# copy the default config if not already present
cp -n /usr/local/bin/qBittorrent.conf /config/qBittorrent/qBittorrent.conf

# set custom settings
sed -i -E "s|^WebUI\\\Username=.*$|WebUI\\\Username=$QBIT_WEBUI_USER|g" /config/qBittorrent/qBittorrent.conf
sed -i -E "s|^WebUI\\\Password_PBKDF2=.*$|WebUI\\\Password_PBKDF2=@ByteArray($QBIT_WEBUI_PASS_PBKDF2)|g" /config/qBittorrent/qBittorrent.conf
sed -i -E "s|^Connection\\\PortRangeMin=.*$|Connection\\\PortRangeMin=$QBIT_CONNECTION_PORT|g" /config/qBittorrent/qBittorrent.conf
sed -i -E "s|^Bittorrent\\\MaxRatio=.*$|Bittorrent\\\MaxRatio=$QBIT_MAX_RATIO|g" /config/qBittorrent/qBittorrent.conf
sed -i -E "s|^Session\\\GlobalMaxSeedingMinutes=.*$|Session\\\GlobalMaxSeedingMinutes=$QBIT_MAX_RETENTION|g" /config/qBittorrent/qBittorrent.conf

# take control of permissions
chown -R abc:abc \
	/config \
	/usr/local/bin
