#!/usr/bin/with-contenv bash

sed -i '\[AutoRun\]/d' /config/qBittorrent/qBittorrent.conf
sed -i 'enabled=false/d' /config/qBittorrent/qBittorrent.conf
sed -i 'enabled=true/d' /config/qBittorrent/qBittorrent.conf
sed -i 'program=/d' /config/qBittorrent/qBittorrent.conf
sed -i 'WebUI\\Password_ha1=' /config/qBittorrent/qBittorrent.conf
sed -i 'WebUI\\Username=' /config/qBittorrent/qBittorrent.conf
sed -i 'Downloads\\SavePath=' /config/qBittorrent/qBittorrent.conf

QBIT_WEBUI_USER=${QBIT_WEBUI_USER:-admin}
QBIT_WEBUI_PASS=${QBIT_WEBUI_PASS:-adminadmin}
QBIT_WEBUI_PASS_MD5=$(echo -n ${QBIT_WEBUI_PASS} | md5sum | awk '{print $1}')

# insert webui user / password configuration
printf '%s\n' '' '[Preferences]' "WebUI\\Username=${QBIT_WEBUI_USER}" "WebUI\\Password_ha1=@ByteArray(${QBIT_WEBUI_PASS_MD5})" 'Downloads\SavePath=/downloads/' 'Queueing\QueueingEnabled=false' >> /config/qBittorrent/qBittorrent.conf

cat <<"EOF"
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
         _               _
    __ _| |__   ___  ___| |_
   / _` | '_ \ / _ \/ __| __/
  | (_| | | | | (_) \__ \ |_
   \__, |_|_|_|\___/|___/\__|
   |___/      /   _ \
          (¯\| o (@) |/¯)
           \_  .___.  _/
            /   !_!   \
           /_.--._.--._\

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
EOF

# take control of permissions
chown -R abc:abc \
	/config \
	/media \
	/downloads
